name: Build e Analisi SonarCloud

# Questo workflow si attiva su ogni push e pull request sul branch 'main'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Un workflow può avere uno o più job. Qui ne definiamo uno chiamato 'build'.
jobs:
  build:
    # Specifica su quale tipo di macchina virtuale eseguire il job.
    # 'ubuntu-latest' è la scelta più comune per i progetti C/C++.
    runs-on: ubuntu-latest

    # I 'steps' sono i passaggi che il tuo job deve seguire in ordine.
    steps:
      # Step 1: Clona il tuo codice dalla repository. Questo è sempre il primo passo.
      - name: Checkout del Codice
        uses: actions/checkout@v4
      
      # Step 2: Installa gli strumenti di compilazione C
      - name: Installa gli strumenti di compilazione C
        run: sudo apt-get update && sudo apt-get install -y gcc make

      # Step 3: debug per vedere la struttura del tuo progetto
      - name: Visualizza file del repository
        run: ls -R

      # Step 4: Scarica e decomprimi il build-wrapper di SonarCloud
      - name: Scarica build-wrapper
        shell: bash
        run: |
          wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip build-wrapper-linux-x86.zip

      # Step 5: Esegui la build del programma utilizzando il build-wrapper
      - name: Esegui build con build-wrapper
        shell: bash
        run: |
          ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bw-output make clean all
      
      # Step 6: Analisi del codice con SonarCloud
      # Utilizza il token salvato come segreto del repository
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=antonioborrelli11-coder_mergesort
            -Dsonar.organization=antonioborrelli11-coder
            -Dsonar.cfamily.build-wrapper-output=bw-output
